// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHOENIX.Data;

#nullable disable

namespace PHOENIX.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430093819_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PHOENIX.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplineType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAge")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("MinAge")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 6,
                            MaxWeight = 999.0,
                            MinAge = 6,
                            MinWeight = 0.0,
                            Name = "KATA MALE 6 YEARS"
                        },
                        new
                        {
                            Id = 2,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 7,
                            MaxWeight = 999.0,
                            MinAge = 7,
                            MinWeight = 0.0,
                            Name = "KATA MALE 7 YEARS"
                        },
                        new
                        {
                            Id = 3,
                            DisciplineType = 0,
                            Gender = 1,
                            MaxAge = 7,
                            MaxWeight = 999.0,
                            MinAge = 6,
                            MinWeight = 0.0,
                            Name = "KATA FEMALE 6-7 YEARS"
                        },
                        new
                        {
                            Id = 4,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 8,
                            MaxWeight = 999.0,
                            MinAge = 8,
                            MinWeight = 0.0,
                            Name = "KATA MALE 8 YEARS"
                        },
                        new
                        {
                            Id = 5,
                            DisciplineType = 0,
                            Gender = 1,
                            MaxAge = 9,
                            MaxWeight = 999.0,
                            MinAge = 8,
                            MinWeight = 0.0,
                            Name = "KATA FEMALE 8-9 YEARS"
                        },
                        new
                        {
                            Id = 6,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 9,
                            MaxWeight = 999.0,
                            MinAge = 9,
                            MinWeight = 0.0,
                            Name = "KATA MALE 9 YEARS"
                        },
                        new
                        {
                            Id = 7,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 10,
                            MaxWeight = 999.0,
                            MinAge = 10,
                            MinWeight = 0.0,
                            Name = "KATA MALE 10 YEARS"
                        },
                        new
                        {
                            Id = 8,
                            DisciplineType = 0,
                            Gender = 1,
                            MaxAge = 11,
                            MaxWeight = 999.0,
                            MinAge = 10,
                            MinWeight = 0.0,
                            Name = "KATA FEMALE 10-11 YEARS"
                        },
                        new
                        {
                            Id = 9,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 11,
                            MaxWeight = 999.0,
                            MinAge = 11,
                            MinWeight = 0.0,
                            Name = "KATA MALE 11 YEARS"
                        },
                        new
                        {
                            Id = 10,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 13,
                            MaxWeight = 999.0,
                            MinAge = 12,
                            MinWeight = 0.0,
                            Name = "KATA MALE 12-13 YEARS"
                        },
                        new
                        {
                            Id = 11,
                            DisciplineType = 0,
                            Gender = 1,
                            MaxAge = 13,
                            MaxWeight = 999.0,
                            MinAge = 12,
                            MinWeight = 0.0,
                            Name = "KATA FEMALE 12-13 YEARS"
                        },
                        new
                        {
                            Id = 12,
                            DisciplineType = 2,
                            Gender = 0,
                            MaxAge = 6,
                            MaxWeight = 999.0,
                            MinAge = 6,
                            MinWeight = 0.0,
                            Name = "KUMITE PHANTOM MALE 6 YEARS"
                        },
                        new
                        {
                            Id = 13,
                            DisciplineType = 2,
                            Gender = 1,
                            MaxAge = 6,
                            MaxWeight = 999.0,
                            MinAge = 6,
                            MinWeight = 0.0,
                            Name = "KUMITE PHANTOM FEMALE 6 YEARS"
                        },
                        new
                        {
                            Id = 14,
                            DisciplineType = 2,
                            Gender = 0,
                            MaxAge = 7,
                            MaxWeight = 999.0,
                            MinAge = 7,
                            MinWeight = 0.0,
                            Name = "KUMITE PHANTOM MALE 7 YEARS"
                        },
                        new
                        {
                            Id = 15,
                            DisciplineType = 2,
                            Gender = 1,
                            MaxAge = 7,
                            MaxWeight = 999.0,
                            MinAge = 7,
                            MinWeight = 0.0,
                            Name = "KUMITE PHANTOM FEMALE 7 YEARS"
                        },
                        new
                        {
                            Id = 16,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 7,
                            MaxWeight = 23.0,
                            MinAge = 7,
                            MinWeight = 0.0,
                            Name = "KUMITE MALE 7 YEARS -23 KG"
                        },
                        new
                        {
                            Id = 17,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 7,
                            MaxWeight = 26.0,
                            MinAge = 7,
                            MinWeight = 23.010000000000002,
                            Name = "KUMITE MALE 7 YEARS -26 KG"
                        },
                        new
                        {
                            Id = 18,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 7,
                            MaxWeight = 999.0,
                            MinAge = 7,
                            MinWeight = 26.010000000000002,
                            Name = "KUMITE MALE 7 YEARS 26+ KG"
                        },
                        new
                        {
                            Id = 19,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 7,
                            MaxWeight = 22.0,
                            MinAge = 7,
                            MinWeight = 0.0,
                            Name = "KUMITE FEMALE 7 YEARS -22 KG"
                        },
                        new
                        {
                            Id = 20,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 7,
                            MaxWeight = 999.0,
                            MinAge = 7,
                            MinWeight = 22.010000000000002,
                            Name = "KUMITE FEMALE 7 YEARS 22+ KG"
                        },
                        new
                        {
                            Id = 21,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 8,
                            MaxWeight = 27.0,
                            MinAge = 8,
                            MinWeight = 0.0,
                            Name = "KUMITE MALE 8 YEARS -27 KG"
                        },
                        new
                        {
                            Id = 22,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 8,
                            MaxWeight = 30.0,
                            MinAge = 8,
                            MinWeight = 27.010000000000002,
                            Name = "KUMITE MALE 8 YEARS -30 KG"
                        },
                        new
                        {
                            Id = 23,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 8,
                            MaxWeight = 999.0,
                            MinAge = 8,
                            MinWeight = 30.010000000000002,
                            Name = "KUMITE MALE 8 YEARS 30+ KG"
                        },
                        new
                        {
                            Id = 24,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 9,
                            MaxWeight = 25.0,
                            MinAge = 8,
                            MinWeight = 0.0,
                            Name = "KUMITE FEMALE 8-9 YEARS -25 KG"
                        },
                        new
                        {
                            Id = 25,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 9,
                            MaxWeight = 29.0,
                            MinAge = 8,
                            MinWeight = 25.010000000000002,
                            Name = "KUMITE FEMALE 8-9 YEARS -29 KG"
                        },
                        new
                        {
                            Id = 26,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 9,
                            MaxWeight = 999.0,
                            MinAge = 8,
                            MinWeight = 29.010000000000002,
                            Name = "KUMITE FEMALE 8-9 YEARS 29+ KG"
                        },
                        new
                        {
                            Id = 27,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 9,
                            MaxWeight = 29.0,
                            MinAge = 9,
                            MinWeight = 0.0,
                            Name = "KUMITE MALE 9 YEARS -29 KG"
                        },
                        new
                        {
                            Id = 28,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 9,
                            MaxWeight = 33.0,
                            MinAge = 9,
                            MinWeight = 29.010000000000002,
                            Name = "KUMITE MALE 9 YEARS -33 KG"
                        },
                        new
                        {
                            Id = 29,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 9,
                            MaxWeight = 999.0,
                            MinAge = 9,
                            MinWeight = 33.009999999999998,
                            Name = "KUMITE MALE 9 YEARS 33+ KG"
                        },
                        new
                        {
                            Id = 30,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 11,
                            MaxWeight = 30.0,
                            MinAge = 10,
                            MinWeight = 0.0,
                            Name = "KUMITE MALE 10-11 YEARS -30 KG"
                        },
                        new
                        {
                            Id = 31,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 11,
                            MaxWeight = 34.0,
                            MinAge = 10,
                            MinWeight = 30.010000000000002,
                            Name = "KUMITE MALE 10-11 YEARS -34 KG"
                        },
                        new
                        {
                            Id = 32,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 11,
                            MaxWeight = 39.0,
                            MinAge = 10,
                            MinWeight = 34.009999999999998,
                            Name = "KUMITE MALE 10-11 YEARS -39 KG"
                        },
                        new
                        {
                            Id = 33,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 11,
                            MaxWeight = 44.0,
                            MinAge = 10,
                            MinWeight = 39.009999999999998,
                            Name = "KUMITE MALE 10-11 YEARS -44 KG"
                        },
                        new
                        {
                            Id = 34,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 11,
                            MaxWeight = 999.0,
                            MinAge = 10,
                            MinWeight = 44.009999999999998,
                            Name = "KUMITE MALE 10-11 YEARS 44+ KG"
                        },
                        new
                        {
                            Id = 35,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 11,
                            MaxWeight = 33.0,
                            MinAge = 10,
                            MinWeight = 0.0,
                            Name = "KUMITE FEMALE 10-11 YEARS -33 KG"
                        },
                        new
                        {
                            Id = 36,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 11,
                            MaxWeight = 39.0,
                            MinAge = 10,
                            MinWeight = 33.009999999999998,
                            Name = "KUMITE FEMALE 10-11 YEARS -39 KG"
                        },
                        new
                        {
                            Id = 37,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 11,
                            MaxWeight = 999.0,
                            MinAge = 10,
                            MinWeight = 39.009999999999998,
                            Name = "KUMITE FEMALE 10-11 YEARS 39+ KG"
                        },
                        new
                        {
                            Id = 38,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 13,
                            MaxWeight = 40.0,
                            MinAge = 12,
                            MinWeight = 0.0,
                            Name = "KUMITE MALE 12-13 YEARS -40 KG"
                        },
                        new
                        {
                            Id = 39,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 13,
                            MaxWeight = 45.0,
                            MinAge = 12,
                            MinWeight = 40.009999999999998,
                            Name = "KUMITE MALE 12-13 YEARS -45 KG"
                        },
                        new
                        {
                            Id = 40,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 13,
                            MaxWeight = 50.0,
                            MinAge = 12,
                            MinWeight = 45.009999999999998,
                            Name = "KUMITE MALE 12-13 YEARS -50 KG"
                        },
                        new
                        {
                            Id = 41,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 13,
                            MaxWeight = 55.0,
                            MinAge = 12,
                            MinWeight = 50.009999999999998,
                            Name = "KUMITE MALE 12-13 YEARS -55 KG"
                        },
                        new
                        {
                            Id = 42,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 13,
                            MaxWeight = 999.0,
                            MinAge = 12,
                            MinWeight = 55.009999999999998,
                            Name = "KUMITE MALE 12-13 YEARS 55+ KG"
                        },
                        new
                        {
                            Id = 43,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 13,
                            MaxWeight = 42.0,
                            MinAge = 12,
                            MinWeight = 0.0,
                            Name = "KUMITE FEMALE 12-13 YEARS -42 KG"
                        },
                        new
                        {
                            Id = 44,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 13,
                            MaxWeight = 47.0,
                            MinAge = 12,
                            MinWeight = 42.009999999999998,
                            Name = "KUMITE FEMALE 12-13 YEARS -47 KG"
                        },
                        new
                        {
                            Id = 45,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 13,
                            MaxWeight = 52.0,
                            MinAge = 12,
                            MinWeight = 47.009999999999998,
                            Name = "KUMITE FEMALE 12-13 YEARS -52 KG"
                        },
                        new
                        {
                            Id = 46,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 13,
                            MaxWeight = 999.0,
                            MinAge = 12,
                            MinWeight = 52.009999999999998,
                            Name = "KUMITE FEMALE 12-13 YEARS 52+ KG"
                        },
                        new
                        {
                            Id = 47,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 15,
                            MaxWeight = 999.0,
                            MinAge = 14,
                            MinWeight = 0.0,
                            Name = "CADET KATA MALE"
                        },
                        new
                        {
                            Id = 48,
                            DisciplineType = 0,
                            Gender = 1,
                            MaxAge = 15,
                            MaxWeight = 999.0,
                            MinAge = 14,
                            MinWeight = 0.0,
                            Name = "CADET KATA FEMALE"
                        },
                        new
                        {
                            Id = 49,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 15,
                            MaxWeight = 52.0,
                            MinAge = 14,
                            MinWeight = 0.0,
                            Name = "CADET KUMITE MALE -52 KG"
                        },
                        new
                        {
                            Id = 50,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 15,
                            MaxWeight = 57.0,
                            MinAge = 14,
                            MinWeight = 52.009999999999998,
                            Name = "CADET KUMITE MALE -57 KG"
                        },
                        new
                        {
                            Id = 51,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 15,
                            MaxWeight = 63.0,
                            MinAge = 14,
                            MinWeight = 57.009999999999998,
                            Name = "CADET KUMITE MALE -63 KG"
                        },
                        new
                        {
                            Id = 52,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 15,
                            MaxWeight = 70.0,
                            MinAge = 14,
                            MinWeight = 63.009999999999998,
                            Name = "CADET KUMITE MALE -70 KG"
                        },
                        new
                        {
                            Id = 53,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 15,
                            MaxWeight = 999.0,
                            MinAge = 14,
                            MinWeight = 70.010000000000005,
                            Name = "CADET KUMITE MALE 70+ KG"
                        },
                        new
                        {
                            Id = 54,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 15,
                            MaxWeight = 47.0,
                            MinAge = 14,
                            MinWeight = 0.0,
                            Name = "CADET KUMITE FEMALE -47 KG"
                        },
                        new
                        {
                            Id = 55,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 15,
                            MaxWeight = 54.0,
                            MinAge = 14,
                            MinWeight = 47.009999999999998,
                            Name = "CADET KUMITE FEMALE -54 KG"
                        },
                        new
                        {
                            Id = 56,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 15,
                            MaxWeight = 61.0,
                            MinAge = 14,
                            MinWeight = 54.009999999999998,
                            Name = "CADET KUMITE FEMALE -61 KG"
                        },
                        new
                        {
                            Id = 57,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 15,
                            MaxWeight = 999.0,
                            MinAge = 14,
                            MinWeight = 61.009999999999998,
                            Name = "CADET KUMITE FEMALE 61+ KG"
                        },
                        new
                        {
                            Id = 58,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 17,
                            MaxWeight = 999.0,
                            MinAge = 16,
                            MinWeight = 0.0,
                            Name = "JUNIOR KATA MALE"
                        },
                        new
                        {
                            Id = 59,
                            DisciplineType = 0,
                            Gender = 1,
                            MaxAge = 17,
                            MaxWeight = 999.0,
                            MinAge = 16,
                            MinWeight = 0.0,
                            Name = "JUNIOR KATA FEMALE"
                        },
                        new
                        {
                            Id = 60,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 17,
                            MaxWeight = 55.0,
                            MinAge = 16,
                            MinWeight = 0.0,
                            Name = "JUNIOR KUMITE MALE -55 KG"
                        },
                        new
                        {
                            Id = 61,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 17,
                            MaxWeight = 61.0,
                            MinAge = 16,
                            MinWeight = 55.009999999999998,
                            Name = "JUNIOR KUMITE MALE -61 KG"
                        },
                        new
                        {
                            Id = 62,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 17,
                            MaxWeight = 68.0,
                            MinAge = 16,
                            MinWeight = 61.009999999999998,
                            Name = "JUNIOR KUMITE MALE -68 KG"
                        },
                        new
                        {
                            Id = 63,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 17,
                            MaxWeight = 76.0,
                            MinAge = 16,
                            MinWeight = 68.010000000000005,
                            Name = "JUNIOR KUMITE MALE -76 KG"
                        },
                        new
                        {
                            Id = 64,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 17,
                            MaxWeight = 999.0,
                            MinAge = 16,
                            MinWeight = 76.010000000000005,
                            Name = "JUNIOR KUMITE MALE 76+ KG"
                        },
                        new
                        {
                            Id = 65,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 17,
                            MaxWeight = 48.0,
                            MinAge = 16,
                            MinWeight = 0.0,
                            Name = "JUNIOR KUMITE FEMALE -48 KG"
                        },
                        new
                        {
                            Id = 66,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 17,
                            MaxWeight = 53.0,
                            MinAge = 16,
                            MinWeight = 48.009999999999998,
                            Name = "JUNIOR KUMITE FEMALE -53 KG"
                        },
                        new
                        {
                            Id = 67,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 17,
                            MaxWeight = 59.0,
                            MinAge = 16,
                            MinWeight = 53.009999999999998,
                            Name = "JUNIOR KUMITE FEMALE -59 KG"
                        },
                        new
                        {
                            Id = 68,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 17,
                            MaxWeight = 66.0,
                            MinAge = 16,
                            MinWeight = 59.009999999999998,
                            Name = "JUNIOR KUMITE FEMALE -66 KG"
                        },
                        new
                        {
                            Id = 69,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 17,
                            MaxWeight = 999.0,
                            MinAge = 16,
                            MinWeight = 66.010000000000005,
                            Name = "JUNIOR KUMITE FEMALE 66+ KG"
                        },
                        new
                        {
                            Id = 70,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 20,
                            MaxWeight = 999.0,
                            MinAge = 18,
                            MinWeight = 0.0,
                            Name = "U21 KATA MALE"
                        },
                        new
                        {
                            Id = 71,
                            DisciplineType = 0,
                            Gender = 1,
                            MaxAge = 20,
                            MaxWeight = 999.0,
                            MinAge = 18,
                            MinWeight = 0.0,
                            Name = "U21 KATA FEMALE"
                        },
                        new
                        {
                            Id = 72,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 20,
                            MaxWeight = 60.0,
                            MinAge = 18,
                            MinWeight = 0.0,
                            Name = "U21 KUMITE MALE -60 KG"
                        },
                        new
                        {
                            Id = 73,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 20,
                            MaxWeight = 67.0,
                            MinAge = 18,
                            MinWeight = 60.009999999999998,
                            Name = "U21 KUMITE MALE -67 KG"
                        },
                        new
                        {
                            Id = 74,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 20,
                            MaxWeight = 75.0,
                            MinAge = 18,
                            MinWeight = 67.010000000000005,
                            Name = "U21 KUMITE MALE -75 KG"
                        },
                        new
                        {
                            Id = 75,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 20,
                            MaxWeight = 84.0,
                            MinAge = 18,
                            MinWeight = 75.010000000000005,
                            Name = "U21 KUMITE MALE -84 KG"
                        },
                        new
                        {
                            Id = 76,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 20,
                            MaxWeight = 999.0,
                            MinAge = 18,
                            MinWeight = 84.010000000000005,
                            Name = "U21 KUMITE MALE 84+ KG"
                        },
                        new
                        {
                            Id = 77,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 20,
                            MaxWeight = 50.0,
                            MinAge = 18,
                            MinWeight = 0.0,
                            Name = "U21 KUMITE FEMALE -50 KG"
                        },
                        new
                        {
                            Id = 78,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 20,
                            MaxWeight = 55.0,
                            MinAge = 18,
                            MinWeight = 50.009999999999998,
                            Name = "U21 KUMITE FEMALE -55 KG"
                        },
                        new
                        {
                            Id = 79,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 20,
                            MaxWeight = 61.0,
                            MinAge = 18,
                            MinWeight = 55.009999999999998,
                            Name = "U21 KUMITE FEMALE -61 KG"
                        },
                        new
                        {
                            Id = 80,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 20,
                            MaxWeight = 68.0,
                            MinAge = 18,
                            MinWeight = 61.009999999999998,
                            Name = "U21 KUMITE FEMALE -68 KG"
                        },
                        new
                        {
                            Id = 81,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 20,
                            MaxWeight = 999.0,
                            MinAge = 18,
                            MinWeight = 68.010000000000005,
                            Name = "U21 KUMITE FEMALE 68+ KG"
                        },
                        new
                        {
                            Id = 82,
                            DisciplineType = 0,
                            Gender = 0,
                            MaxAge = 99,
                            MaxWeight = 999.0,
                            MinAge = 16,
                            MinWeight = 0.0,
                            Name = "MALE KATA"
                        },
                        new
                        {
                            Id = 83,
                            DisciplineType = 0,
                            Gender = 1,
                            MaxAge = 99,
                            MaxWeight = 999.0,
                            MinAge = 16,
                            MinWeight = 0.0,
                            Name = "FEMALE KATA"
                        },
                        new
                        {
                            Id = 84,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 99,
                            MaxWeight = 60.0,
                            MinAge = 18,
                            MinWeight = 0.0,
                            Name = "MALE KUMITE -60 KG"
                        },
                        new
                        {
                            Id = 85,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 99,
                            MaxWeight = 67.0,
                            MinAge = 18,
                            MinWeight = 60.009999999999998,
                            Name = "MALE KUMITE -67 KG"
                        },
                        new
                        {
                            Id = 86,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 99,
                            MaxWeight = 75.0,
                            MinAge = 18,
                            MinWeight = 67.010000000000005,
                            Name = "MALE KUMITE -75 KG"
                        },
                        new
                        {
                            Id = 87,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 99,
                            MaxWeight = 84.0,
                            MinAge = 18,
                            MinWeight = 75.010000000000005,
                            Name = "MALE KUMITE -84 KG"
                        },
                        new
                        {
                            Id = 88,
                            DisciplineType = 1,
                            Gender = 0,
                            MaxAge = 99,
                            MaxWeight = 999.0,
                            MinAge = 18,
                            MinWeight = 84.010000000000005,
                            Name = "MALE KUMITE 84+ KG"
                        },
                        new
                        {
                            Id = 89,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 99,
                            MaxWeight = 50.0,
                            MinAge = 18,
                            MinWeight = 0.0,
                            Name = "FEMALE KUMITE -50 KG"
                        },
                        new
                        {
                            Id = 90,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 99,
                            MaxWeight = 55.0,
                            MinAge = 18,
                            MinWeight = 50.009999999999998,
                            Name = "FEMALE KUMITE -55 KG"
                        },
                        new
                        {
                            Id = 91,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 99,
                            MaxWeight = 61.0,
                            MinAge = 18,
                            MinWeight = 55.009999999999998,
                            Name = "FEMALE KUMITE -61 KG"
                        },
                        new
                        {
                            Id = 92,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 99,
                            MaxWeight = 68.0,
                            MinAge = 18,
                            MinWeight = 61.009999999999998,
                            Name = "FEMALE KUMITE -68 KG"
                        },
                        new
                        {
                            Id = 93,
                            DisciplineType = 1,
                            Gender = 1,
                            MaxAge = 99,
                            MaxWeight = 999.0,
                            MinAge = 18,
                            MinWeight = 68.010000000000005,
                            Name = "FEMALE KUMITE 68+ KG"
                        });
                });

            modelBuilder.Entity("PHOENIX.Models.Sportsman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Sportsmen");
                });

            modelBuilder.Entity("PHOENIX.Models.Sportsman", b =>
                {
                    b.HasOne("PHOENIX.Models.Category", "Category")
                        .WithMany("Sportsmen")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PHOENIX.Models.Category", b =>
                {
                    b.Navigation("Sportsmen");
                });
#pragma warning restore 612, 618
        }
    }
}
